config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:show, :new, :create, :update]
  
  resources :topics, only: [:show, :new, :create, :destroy]
  
  resources :posts, only: [:new, :create, :destroy]
  
  resources :interests, only: [:create, :destroy]
end

app/models/agree.rb
class Agree < Interest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disagree.rb
class Disagree < Interest
  def self.counting
   self.group(:post_id).order('count_post_id DESC!').count(:post_id)
  end
end

app/models/interest.rb
class Interest < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  def self.ranking
    self.group(:post_id).order('count_id DESC').limit(3).count(:id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  
  mount_uploader :image, ImageUploader
  
  validates :image, presence: true#, length: {maximum: 255}
  validates :content, presence: true, length: {maximum: 100}
  
  belongs_to :user
  belongs_to :topic
  
  has_many :interests, dependent: :destroy
  has_many :interested_users, through: :interests
  
  has_many :agrees
  has_many :agree_users, through: :agrees, source: :user
  
  has_many :disagrees
  has_many :disagree_user, through: :disagrees, source: :user
  
  #def self.total_interest
  #  self.joins('LEFT JOIN interests ON post_id = posts.id').group(:topic_id).order('count_type DESC').count(:type)
  #  #self.joins(:interests).group(:topic_id).order('count_type DESC').count(:type)
  #end
 
end

app/models/topic.rb
class Topic < ApplicationRecord

  validates :content, presence: true, length: { maximum: 255 }
  
  belongs_to :user
  has_many :posts, dependent: :destroy
  #has_many :user_of_posts, through: :posts, source: :user
  
  def self.total_interest
    self.eager_load(posts: :interests).group(:id).order('count_interests_id DESC').count('interests.id')
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email.downcase!}
  
  mount_uploader :image, ImageUploader
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :sex, presence: true
  has_secure_password
  
  has_many :topics
  has_many :posts
  #has_many :commented_topics, through: :posts, source: :topic
  
  has_many :interests
  has_many :interested_posts, through: :interests, source: :post
  
  has_many :agrees
  has_many :agree_posts, through: :agrees, source: :post
  
  has_many :disagrees
  has_many :disagree_posts, through: :disagrees, source: :post
  
  def agree(post)
    self.agrees.find_or_create_by(post_id: post.id)
    
    disagree= self.disagrees.find_by(post_id: post.id)
    disagree.destroy if disagree
  end
  
  def del_agree(post)
    agree = self.agrees.find_by(post_id: post.id)
    agree.destroy if agree
  end
  
  def agree?(post)
    self.agree_posts.include?(post)
  end
  
  def disagree(post)
    self.disagrees.find_or_create_by(post_id: post.id)
    
    agree = self.agrees.find_by(post_id: post.id)
    agree.destroy if agree
  end
  
  def del_disagree(post)
    disagree= self.disagrees.find_by(post_id: post.id)
    disagree.destroy if disagree
  end
  
  def disagree?(post)
    self.disagree_posts.include?(post)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    
    if params[:type] == "Agree"
      current_user.agree(@post)
      flash[:success] = "説明をいいね！と評価しました。"
    end
    
    if params[:type] == "Disagree"
      current_user.disagree(@post)
      flash[:success] = "説明を違うね！と評価しました。"
    end
    
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    
    if params[:type] == "Agree"
      current_user.del_agree(@post)
      flash[:success] = "説明のいいね！を削除しました。"
    end
    
    if params[:type] == "Disagree"
      current_user.del_disagree(@post)
      flash[:success] = "説明の違うね！を削除しました。"
    end
    
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  
  def new
    @post = Post.new
    @topic = Topic.find(params[:topic_id])
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(posts_params)
    @post[:topic_id]=@topic.id
    
    if @post.save
      flash[:success] = '説明を投稿しました。'
      redirect_to topic_path(@topic)
    else
      flash.now[:danger] = '説明の投稿に失敗しました。'
      render :new
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = '説明を削除しました。'
    
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def posts_params
    params.require(:post).permit(:content, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_user_logged_in
  
  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.order('created_at DESC').page(params[:page])
    @rank = params[:rank]
    
    @interest_sum = Topic.total_interest
    
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.build(topics_params)
    if @topic.save
      flash[:success] = 'お題を投稿しました。'
      redirect_to root_url
    else
      @topics = Topic.all.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'お題の投稿に失敗しました。'
      render :new
    end
  end
  
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    flash[:success] = 'お題を削除しました。'
    
    redirect_to root_url
  end
  
  private
  
  def topics_params
    params.require(:topic).permit(:content)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    #@topics = Topic.all.order('created_at DESC').page(params[:page])
    
    @interest_sum = Topic.total_interest
    topics = Topic.find(@interest_sum.keys)
    @topics = Kaminari.paginate_array(topics).page(params[:page])
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def show
    @user = User.find(params[:id])
    @agree_posts=@user.agree_posts.page(params[:page])
    unless @user == current_user
      redirect_to root_url
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger]='ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user == current_user 
      @user.image.cache! unless @user.image.blank?
      if @user.update(user_params)
        flash[:success] = 'プロフィール画像を登録しました。'
        redirect_to @user
      else
        flash.now[:danger]='プロフィール画像の登録に失敗しました。'
        render user_path
      end
    else
      redirect_to root_url
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :sex, :age, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/views/interests/_agree_button.html.erb
<% if current_user.agree?(post) %>
  <%= form_tag(interest_path(post.id), method: :delete) do %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= hidden_field_tag :type, 'Agree' %>
    <%= submit_tag 'なるほど！', class: 'btn agree-on' %>
    <div class="count agree-on"><%= post.agrees.count %></div>
  <% end %>
<% else %>
  <%= form_tag(interests_path) do %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= hidden_field_tag :type, 'Agree' %>
    <%= submit_tag 'なるほど！', class: 'btn agree-off' %>
    <div class="count agree-off"><%= post.agrees.count %></div>
  <% end %>
<% end %>

app/views/interests/_disagree_button.html.erb
<% if current_user.disagree?(post) %>
  <%= form_tag(interest_path(post.id), method: :delete) do %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= hidden_field_tag :type, 'Disagree' %>
    <%= submit_tag '違うね！', class: 'btn disagree-on' %>
    <div class="count disagree-on"><%= post.disagrees.count %></div>
  <% end %>
<% else %>
  <%= form_tag(interests_path) do %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= hidden_field_tag :type, 'Disagree' %>
    <%= submit_tag '違うね！', class: 'btn disagree-off' %>
    <div class="count disagree-off"><%= post.disagrees.count %></div>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_explanation.html.erb
<div class="explanation">
  <p>
    ここにはここのWebアプリの説明を浅野さんが後で書きます。今はこのサンプルテキストだけで勘弁してください。
    らららららららららららららららららららららららららららららららららららららららららららららららららら
    らららららららららららららららららららら
  </p>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-static-bottom">
  <div class="text-center">© 2019 ArisLogos by Zoia.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ArisLogos</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'マイページ', user_path(current_user) %></li>
            <li><%= link_to 'お題作成', new_topic_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'ユーザ登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">
    
    <title>Arislogos</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="wrapper">
    
    <%= render 'layouts/navbar' %>
    <div class="overlay">
      <div class="popup-content"></div>
    </div>
    <div class="container">
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    </div>
    <a href="#" class="back-to-top">▲</a>
  </body>
</html>

app/views/posts/_posts.html.erb
<ul class="media-list">
  <% posts.each do |post| %>
    <li class="media">
      <div class="post media-body">
        <div class="created-date">
          <span class="text-muted">posted <%= distance_of_time_in_words_to_now(post.created_at) %> ago by <%= post.user.name %></span>
        </div>
        <div class="post-image text-center">
          <% if post.image? %>
            <%= image_tag post.image.url, class: "popup media-object " %>
          <% else %>
            <%= image_tag 'noimage.gif' %>
          <% end %>
        </div>
        <div class="post-content text-center">
          <%= post.content%>
        </div>
        <% if logged_in? %>
          <% if post.user == current_user %>
            <div class="delete-button"><%= link_to '削除', post, method: :delete, data: {confirm: '本当に削除してよろしいですか?'}, class: 'post-buttons btn btn-danger text-left' %></div>
          <% end %>
          <div class="post-buttons text-right">
            <%= render "interests/agree_button", post: post %>
            <%= render "interests/disagree_button", post: post %>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/new.html.erb
<div class="text-center">
  <h1>説明の作成ページ！</h1>
</div>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="text-center">
      <h2>お題：<%= @topic.content%></h2>
    </div>
    <%= form_for(@post) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <%= hidden_field_tag :topic_id, @topic.id %>
      <div class="form-group">
        <%= f.file_field :image, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_area :content, size: "20x10", class: "form-control", placeholder: '100文字以下' %>
      </div>
      <div class="text-right col-sm-3 col-sm-offset-9">
        <%= f.submit '投稿', class: "btn btn-lg btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/_topics.html.erb
<div class="row">
  <ul class="media-list col-md-offset-2 col-md-8">
    <% topics.each_with_index do |topic, index| %>
      <li class="media topic">
        <div class="media-left">
          <p><%= index+1 %> 位</p></ br>
          <span class="badge badge-pill badge-primary"><%= @interest_sum[topic.id] %></span>
        </div>
        <div class="media-body">
          <div class="created-date">
            <span class="created-date text-muted">posted <%= distance_of_time_in_words_to_now(topic.created_at) %> ago by <%= topic.user.name %></span>
          </div>
          <div class="topic-content text-center">
            <h2><%= link_to topic.content, topic_path(topic, rank: (index+1)) %></h2>
          </div>
        </div>
        <hr class="topic-divider" >
        <div class="text-center">
          このお題のトップ説明：
        </div>
      
        <div class="">
          <% if topic.posts.exists? %>
            <%= render 'posts/posts', posts: topic.posts.order('created_at DESC').limit(3) %>
          <% else %>
            <p class="text-center">まだ説明はありません。あなたが説明してみたら！</p>
          <% end %>
        </div>
      </li>
    <% end %>
  
    <%= paginate topics %>
  </ul>
</div>

app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

app/views/topics/new.html.erb
<div class="text-center">
  <h1>お題の作成ページ！</h1>
</div>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= form_for(@topic) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.text_area :content, size: "20x10", class: "form-control" %>
      </div>
      <div class="text-right col-sm-3 col-sm-offset-9">
        <%= f.submit '投稿', class: "btn btn-lg btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="row">
<div class="media col-md-offset-2 col-md-8">
  <div class="media-left">
    <p><%= @rank  %> 位</p></ br>
    <span class="badge badge-pill badge-primary"><%= @interest_sum[@topic.id] %></span>
  </div>
  <div class="media-body">
    <div>
      <span class="created-date text-muted">posted <%= distance_of_time_in_words_to_now(@topic.created_at) %> ago</span>
    </div>
    <div class="topic-content text-center">
      <h2><%= @topic.content %></h2>
    </div>
  </div>
  <div class="media-right">
    <% if @topic.user == current_user %>
      <%= link_to 'お題を削除', @topic, method: :delete, data: {confirm: '本当に削除してよろしいですか?'}, class: 'delete-button btn btn-danger' %>
    <% end %>
    <%= link_to '説明を投稿', new_post_path(topic_id: @topic.id), class: 'post-button btn btn-md btn-default' %>
  </div>
  <div>
    <% if @topic.posts %>
      <%= render "posts/posts", posts: @posts %>
    <% end %>
    <%= paginate @posts %>
  </div>
</div>
</div>

app/views/toppages/index.html.erb
<div id="logos-container ">
  
  <!--<div class="column left">
  </div>
  <div class="column middle">-->
  <%= render 'topics/topics', topics: @topics %>
  <!--</div>
  <div class="column right">
  %= render 'layouts/explanation' %>
  </div>-->

</div>

app/views/users/new.html.erb
<div class="new-user text-center">
  <h1>ユーザの新規作成</h1>
</div>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= form_for(@user)do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
        
      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-5">
          <label><%= f.radio_button :sex, "男" %> 男性 </label>
          <label><%= f.radio_button :sex, "女" %> 女性 </label>
        </div>
        <div class="col-sm-6">
          <%= f.label :age, '年代' %>
          <%= f.select :age, [["年代",nil],["10代","10代"],["20代","20代"],["30代","30代"],["40代","40代"],["50代","50代"]], class: "form-control" %>
        </div>
      </div>
          

      <div class="form-group">
        <%= f.label :email, 'メール' %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認）' %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="text-center">
        <%= f.submit '登録する', class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile col-md-offset-2 col-md-8">
  <div class="profile-image text-center">
    <% if @user.image? %>
     <%= image_tag @user.image.thumb.url, class: "media-object img-circle " %>
    <% else %>
      <%= image_tag 'noimage.gif' %>
    <% end %>
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
  <div class="profile">
    <%= link_to 'お題を作成', new_topic_path, class: "topic-create-btn btn btn-lg btn-success" %>
    <div class="edit-image btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        プロフィール画像を登録<span class="caret"></span>
      </button>
      <div class="dropdown-menu rightMenu" aria-labelledby="dropdownMenuButton">
        <%= form_for(@user) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <%= f.file_field :image, class: "dropdown-item" %>
          <%= f.hidden_field :image_cache %>
          <%= f.submit '登録', class: "btn btn-sm dropdown-item" %>
        <% end %>
      </div>
    </div>
    <div class="panel-container">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h4>なるほどね！ポスト</h4>
        </div>
        <div class="panel-body">
          <%= render 'posts/posts', posts: @agree_posts %>
        </div>
      </div>
    </div>
  </div>
  
  
</div>